image: docker:20.10.10

stages:
  - build_test_image
  - quality
  - publish
  - deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

.before_script_template:
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build-test-image:
    stage: build_test_image
    services:
      - docker:20.10.10-dind
    extends: .before_script_template
    script:
      - docker build -t $CONTAINER_TEST_IMAGE .
      - docker push $CONTAINER_TEST_IMAGE

linter:
  stage: quality
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - cd /app
    - npm run lint

unit-tests:
  stage: quality
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - cd /app
    - npm run test

build-and-push-to-registry:
  stage: publish
  services:
    - docker:20.10.10-dind
  extends: .before_script_template
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker run $CONTAINER_RELEASE_IMAGE npm run build
    - echo "window.COMMIT='$CI_COMMIT_SHA'; window.BRANCH='$CI_COMMIT_REF_NAME'; window.PIPELINE_LINK='$CI_PIPELINE_URL'; window.BRANCH_LINK='$BRANCH_LINK'" > version.js
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - develop
    - staging

deploy-development-server:
  stage: deploy
  script:
    - chmod og= $DEPLOY_DEV_KEY
    - apk update && apk add openssh-client
    - ssh -i $DEPLOY_DEV_KEY -o StrictHostKeyChecking=no $DEPLOYMENT_USER@$DEV_SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -i $DEPLOY_DEV_KEY -o StrictHostKeyChecking=no $DEPLOYMENT_USER@$DEV_SERVER_IP "docker pull $CONTAINER_RELEASE_IMAGE"
    - ssh -i $DEPLOY_DEV_KEY -o StrictHostKeyChecking=no $DEPLOYMENT_USER@$DEV_SERVER_IP "cd /home/ubuntu/smartskills-deployment && docker-compose up -d"
  environment:
    name: development
    url: http://$DEV_SERVER_IP
  only:
    - develop

deploy-staging-server:
  stage: deploy
  script:
    - chmod og= $DEPLOY_STAGING_KEY
    - apk update && apk add openssh-client
    - ssh -i $DEPLOY_STAGING_KEY -o StrictHostKeyChecking=no $DEPLOYMENT_USER@$STAGING_SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -i $DEPLOY_STAGING_KEY -o StrictHostKeyChecking=no $DEPLOYMENT_USER@$STAGING_SERVER_IP "docker pull $CONTAINER_RELEASE_IMAGE"
    - ssh -i $DEPLOY_STAGING_KEY -o StrictHostKeyChecking=no $DEPLOYMENT_USER@$STAGING_SERVER_IP "cd /home/ubuntu/smartskills-deployment && docker-compose up -d"
  environment:
    name: staging
    url: http://$STAGING_SERVER_IP
  only:
    - staging

