image: node:latest

before_script:
  - apt-get update -qq && apt-get install
  - node -v && npm -v
  - npm install

stages:
  - lint
  - build
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

lint-job:
  stage: lint
  script:
    - echo "Linting code..."
    - npm run lint

build-job:
  stage: build
  script:
    - echo "Building app..."
    - npm run build

unit-test-job:
  stage: test
  script:
    - echo "Running tests..."
    - npm run test

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
