image: node:latest

before_script:
  - apt-get update -qq && apt-get install
  - node -v && npm -v
  - npm install

stages:
#  - lint
  - build
#  - test
#  - e2e
  - deploy
#
#cache:
#  key: ${CI_COMMIT_REF_SLUG}
#  paths:
#    - node_modules/
#  policy: pull
#
#Lint:
#  stage: lint
#  script:
#    - echo "Linting code..."
#    - npm run lint

Build:
  stage: build
  script:
    - echo "Building app..."
    - npm run build
    - cd build
    - touch "version.js"
    - echo "window.COMMIT='$CI_COMMIT_SHA'; window.BRANCH='$CI_COMMIT_REF_NAME'; window.PIPELINE_LINK='$CI_PIPELINE_URL'; window.BASEPATH='/'" > version.js
  artifacts:
    paths:
      - build
    expire_in: 1 week
  only:
    - master

Build Branch:
  stage: build
  variables:
    ASSET_PATH: /branches/$CI_COMMIT_REF_SLUG
    MERGE_REQUEST_ID: $CI_OPEN_MERGE_REQUESTS | awk -F "!" '{print $2}'
    BRANCH_LINK: echo $CI_PROJECT_URL/-/merge-requests/$MERGE_REQUEST_ID
  script:
    - echo $BRANCH_LINK
    - echo $MERGE_REQUEST_ID
    - echo "Building app..."
    - npm run build
    - ls
    - cd build
    - echo "window.COMMIT='$CI_COMMIT_SHA'; window.BRANCH='$CI_COMMIT_REF_NAME'; window.PIPELINE_LINK='$CI_PIPELINE_URL'; window.BASEPATH='/branches/$CI_COMMIT_REF_SLUG/'; window.BRANCH_LINK='$BRANCH_LINK'" > version.js
    - sed -i'' 's/<base href="\/">/<base href="\/branches\/'$CI_COMMIT_REF_SLUG'\/">/' index.html
    - sed -i'' 's/<script src="\/version.js">/<script src="\/branches\/'$CI_COMMIT_REF_SLUG'\/version.js">/' index.html
    - sed -i'' "s/\/static\/js/\/branches\/$CI_COMMIT_REF_SLUG\/static\/js/g" index.html
    - sed -i'' "s/\/static\/css/\/branches\/$CI_COMMIT_REF_SLUG\/static\/css/g" index.html
    - more index.html
  only:
    - branches
  except:
    - master
  artifacts:
    paths:
      - build
    expire_in: 1 week
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: http://172.20.134.20/branches/$CI_COMMIT_REF_SLUG

#Unit Tests:
#  stage: test
#  script:
#    - echo "Running tests..."
#    - npm run test

Deploy:
  stage: deploy
  allow_failure: true
  script:
    - echo "Deploying application..."
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - scp -prq ./build/* $USER_NAME@$SERVER_NAME:/home/$USER_NAME/smartskills/ui/
    - echo "Application successfully deployed."
  only:
    - master
  except:
    - branches

Deploy Branch:
  stage: deploy
  allow_failure: true
  script:
    - echo "Deploying application..."
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh $USER_NAME@$SERVER_NAME "mkdir -p ~/smartskills/ui/branches/$CI_COMMIT_REF_SLUG"
    - scp -prq ./build/* $USER_NAME@$SERVER_NAME:/home/$USER_NAME/smartskills/ui/branches/$CI_COMMIT_REF_SLUG
    - echo "Application successfully deployed."
  only:
    - branches
  except:
    - master

#Cypress Tests:
#  image: cypress/browsers:node14.17.0-chrome88-ff89
#  stage: e2e
#  allow_failure: true
#  variables:
#    APP_PORT: 3001
#  script:
#    - npm run serve -- -l $APP_PORT &
#    - npx cypress run --browser chrome --config baseUrl=http://localhost:$APP_PORT
#  artifacts:
#    when: always
#    paths:
#      - cypress/videos/**/*.mp4
#      - cypress/screenshots/**/*.png
#    expire_in: 1 day