image: docker:20.10.10
services:
  - docker:20.10.10-dind

stages:
  - build
  - quality
  - security
  - release
  - deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

.before_script_template:
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build-test-image:
    stage: build
    extends: .before_script_template
    script:
      - docker build -t $CONTAINER_TEST_IMAGE .
      - docker push $CONTAINER_TEST_IMAGE

linter:
  stage: quality
  extends: .before_script_template
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run npm run lint

unit-tests:
  stage: quality
  extends: .before_script_template
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run npm run test

release-image:
  stage: release
  extends: .before_script_template
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - develop