image: node:latest

before_script:
  - apt-get update -qq && apt-get install
  - node -v && npm -v

stages:
  - install
  - lint
  - build
  - test
  - deploy

cache:
  key: npm
  policy: pull-push
  paths:
    - .npm/

install-job:
  stage: install
  script:
    - npm ci --cache .npm --prefer-offline

lint-job:
  stage: lint
  script:
    - echo "Linting code..."
    - npm run lint

unit-test-job:
  stage: test
  script:
    - echo "Running tests..."
    - npm run test

build-job:
  stage: build
  script:
    - echo "Building app..."
    - npm run build

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
